In [48]:
# %pip install flask
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle
import joblib
from flask import Flask, jsonify, request

In [17]:
x = np.arange(10).reshape(5,2)
y = range(5)

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [19]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [30]:
model.predict(x_test)

array([4., 1.])

---

#### Save and Load Model using Pickle

In [33]:
# Save the model using pickle
with open('LRmodel.pkl','wb') as f:
    pickle.dump(model,f)

In [39]:
# Load the saved model
with open('LRmodel.pkl','rb') as f:
    model = pickle.load(f)

In [40]:
model

LinearRegression()

In [43]:
model.predict([[905235, 8027405870247]])

array([2.00685169e+12])

---

#### Save and Load Model using Joblib

In [46]:
# Save model using joblib
f1 = 'LR_model.sav'
joblib.dump(model, f1)

# Load model
joblib_model = joblib.load(f1)

# predict values
joblib_model.predict([[1,2]])

array([0.5])

---

#### Build backend using Flask

In [57]:
app = Flask(__name__)

@app.route('/input/<int:x1>/<int:x2>/')

def check(x1, x2):
    print(x1,"---", x2)
    fp = open('LRmodel.pkl','rb')
    saved_model = pickle.load(fp)

    # predict the Output Y where input is X1 & X2
    predictedY = saved_model.predict([[x1,x2]])

    print('Output: ', predictedY)
    return 'Y : ' + str(predictedY[0])

In [58]:
app.run(host='0.0.0.0', port=6969)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6969
 * Running on http://127.0.0.1:6969
Press CTRL+C to quit
127.0.0.1 - - [01/May/2024 13:16:00] "GET /input/10/11/ HTTP/1.1" 200 -


10 --- 11
Output:  [5.]
